version: '3'

services:
  server:
    build: .
    restart: always
    ports:
      - "3000:3000"
  db:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres